### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [MissionCriticalCloud/cosmic#858] opened 2019-07-02 17:23 UTC
Hi
The following lines have cryptographic API misuses. <br> File name => cosmic-common/src/main/java/com/cloud/utils/crypt/RSAHelper.java: Line number => 35: API name => Cipher:First parameter (with value "RSA/None/PKCS1Padding") should be any of RSA/{Empty String, ECB}<BR> File name => cosmic-common/src/main/java/com/cloud/utils/nio/Link.java: Line number => 186: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => cosmic-common/src/main/java/com/cloud/utils/security/CertificateHelper.java: Line number => 128: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => cosmic-common/src/main/java/com/cloud/utils/ssh/SSHKeysHelper.java: Line number => 55: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => cosmic-common/src/main/java/com/cloud/utils/EncryptionUtil.java: Line number => 45: API name => SecretKeySpec:<BR> File name => cosmic-common/src/main/java/com/cloud/utils/security/CertificateHelper.java: Line number => 45: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => cosmic-common/src/main/java/com/cloud/utils/ssh/SSHKeysHelper.java: Line number => 63: API name => MessageDigest:<BR> File name => cosmic-common/src/main/java/com/cloud/utils/crypt/RSAHelper.java: Line number => 37: API name => Cipher:<BR> File name => cosmic-common/src/main/java/com/cloud/utils/EncryptionUtil.java: Line number => 45: API name => SecretKeySpec:<BR> File name => cosmic-common/src/main/java/com/cloud/utils/security/CertificateHelper.java: Line number => 129: API name => MessageDigest:<BR> File name => cosmic-common/src/main/java/com/cloud/utils/security/CertificateHelper.java: Line number => 69: API name => KeyStore:Unexpected call to method store on object of type java.security.KeyStore. Expect a call to one of the following methods getKey,getEntry<BR> File name => cosmic-common/src/main/java/com/cloud/utils/security/CertificateHelper.java: Line number => 129: API name => MessageDigest:<BR> File name => cosmic-common/src/main/java/com/cloud/utils/security/CertificateHelper.java: Line number => 96: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => cosmic-common/src/main/java/com/cloud/utils/crypt/RSAHelper.java: Line number => 37: API name => Cipher:<BR> File name => cosmic-common/src/main/java/com/cloud/utils/ssh/SSHKeysHelper.java: Line number => 63: API name => MessageDigest:<BR>

**Comment by sanderv32** [comment] 2019-07-13 23:49
Duplicate of #681

**Closed by sanderv32** 2019-07-13 23:49 UTC
